# Example Application of Results of NorCOM to a population DVector

In [1]:
from pathlib import Path
import math
from functools import reduce

import pandas as pd
from caf.base import DVector

### Define paths to the NorCOM estimation results and the DVector we want to apply the parameters to

In [2]:
# path to results of the parameter estimation
# Note this may be changed to work with the pickle files instead of the 
results_path = Path(r'I:\NorMITs NorCOM\AECOM working\v15')

In [3]:
# path to a household DVector to apply the NorCOM estimation results to
hh_data_path = Path(r"F:\Deliverables\Land-Use\241213_Population\01_Intermediate Files\Output P4.3_NE.hdf")

and read in the dvector data

In [4]:
hh_data = DVector.load(hh_data_path)

### Get the segmentation and zone system from the hh data

In [5]:
dvec_segmentation = hh_data.segmentation

In [6]:
dvec_segmentation.names

['children', 'accom_h', 'ns_sec', 'adults', 'car_availability', 'adult_nssec']

In [7]:
zone_system = hh_data.zoning_system

In [8]:
zone_system.name

'LSOA2021-NE'

### Read in the final estimated model for the two car ownership submodels

In [9]:
model_dirs = ['0v1', '1v2+']
results = {}
variables = []
for model in model_dirs:
    coefficients = pd.read_csv(results_path / model / 'output' / 'final_model_coefficients.csv')
    results[model] = coefficients[['Feature', 'Coefficient']]
    variables += list(coefficients['Feature'].apply(lambda x: '_'.join(x.split('_')[:-1])))
variables = list(set(variables))
variables = ['intercept' if x=='' else x for x in variables]

### Get the relevant segmentation in caf.base that represents the variables used in the model

In [10]:
variables

['intercept',
 'hh_adults_seg',
 'descta_b01id',
 'tfn_at_v2',
 'walkrail_b01id',
 'hh_children_seg',
 'ns',
 'hh_income_banded_v3']

In [11]:
# TODO this should be somehow automated or specified within the constants, this is just for testing
_MAPPING = {
    'ns_sec': 'ns',
    'children': 'hh_children_seg',
    'adults': 'hh_adults_seg'
}

### Aggregate the input dvector to the segmentation required by the estimation results

In [12]:
hh_data_aggregated = hh_data.aggregate(list(_MAPPING.keys()))

In [13]:
# take a copy of the data to generate the parameter interpretations
norcom_dvec = hh_data_aggregated * 0

In [14]:
# get the values of each of these segmentations in the data
hh_data_aggregated.segmentation.seg_dict

{'children': Segment(name='children', values={1: 'Household with no children or all children non-dependent', 2: 'Household with one or more dependent children'}, alias=None, exclusions=[Exclusion(other_name='age_11', exclusions={1: {1, 2, 3}}), Exclusion(other_name='age_9', exclusions={1: {1, 2, 3}}), Exclusion(other_name='age_ntem', exclusions={1: {1}}), Exclusion(other_name='age_5', exclusions={1: {1}}), Exclusion(other_name='economic_status', exclusions={1: {-8}})], lookups=[]),
 'ns_sec': Segment(name='ns_sec', values={1: 'HRP managerial / professional', 2: 'HRP intermediate / technical', 3: 'HRP semi-routine / routine', 4: 'HRP never worked / long-term unemployed', 5: 'HRP no category, inc. full-time student'}, alias=None, exclusions=[], lookups=[]),
 'adults': Segment(name='adults', values={1: 'No adults or 1 adult in household', 2: '2 adults in household', 3: '3 or more adults in household'}, alias=None, exclusions=[], lookups=[])}

In [15]:
# get model instance and the intercept of the model
model = '0v1'
results_data = results.get(model)
intercept = results_data[results_data['Feature'] == 'intercept']['Coefficient'].sum()
# add the intercept to the norcom_dvec
# TODO check the application of the intercept, seems to skew probabilities but this might be because its just an example
norcom_dvec.data = norcom_dvec.data + intercept

In [16]:
# create list of output dvectors to sum
output = [norcom_dvec]

# loop through all the segments
for segment_name in hh_data_aggregated.segmentation.seg_dict.keys():
    segment_values = list(hh_data_aggregated.segmentation.seg_dict.get(segment_name).values.keys())

    # create a segment specific DVector
    segment_dvec = norcom_dvec * 0
    # get the model coefficients that relate to this segment and these values
    for val in segment_values:
        coefficient = results_data[results_data['Feature'] == f'{_MAPPING.get(segment_name)}_{val}']['Coefficient'].sum()
        # replace row values in norcom_dvec to the coefficients
        segment_dvec.data[(segment_dvec.data.index.get_level_values(segment_name) == val)] = coefficient
    output.append(segment_dvec)

In [17]:
# sum the terms of the logit model function across the relevant segments
model_totals = reduce(lambda x, y: x+y, output)
model_totals.data

LSOA2021                E01008162  E01008163  E01008164  E01008165  E01008166  \
ns_sec adults children
1      1      1          1.971195   1.971195   1.971195   1.971195   1.971195
              2          2.346954   2.346954   2.346954   2.346954   2.346954
       2      1          3.107935   3.107935   3.107935   3.107935   3.107935
              2          3.483694   3.483694   3.483694   3.483694   3.483694
       3      1          3.191446   3.191446   3.191446   3.191446   3.191446
              2          3.567205   3.567205   3.567205   3.567205   3.567205
2      1      1          1.662489   1.662489   1.662489   1.662489   1.662489
              2          2.038248   2.038248   2.038248   2.038248   2.038248
       2      1          2.799229   2.799229   2.799229   2.799229   2.799229
              2          3.174988   3.174988   3.174988   3.174988   3.174988
       3      1          2.882740   2.882740   2.882740   2.882740   2.882740
              2          3.258500   3.258500   3.258500   3.258500   3.258500
3      1      1          0.945572   0.945572   0.945572   0.945572   0.945572
              2          1.321332   1.321332   1.321332   1.321332   1.321332
       2      1          2.082313   2.082313   2.082313   2.082313   2.082313
              2          2.458072   2.458072   2.458072   2.458072   2.458072
       3      1          2.165824   2.165824   2.165824   2.165824   2.165824
              2          2.541583   2.541583   2.541583   2.541583   2.541583
4      1      1          0.149380   0.149380   0.149380   0.149380   0.149380
              2          0.525139   0.525139   0.525139   0.525139   0.525139
       2      1          1.286120   1.286120   1.286120   1.286120   1.286120
              2          1.661879   1.661879   1.661879   1.661879   1.661879
       3      1          1.369632   1.369632   1.369632   1.369632   1.369632
              2          1.745391   1.745391   1.745391   1.745391   1.745391
5      1      1          0.728745   0.728745   0.728745   0.728745   0.728745
              2          1.104504   1.104504   1.104504   1.104504   1.104504
       2      1          1.865485   1.865485   1.865485   1.865485   1.865485
              2          2.241245   2.241245   2.241245   2.241245   2.241245
       3      1          1.948997   1.948997   1.948997   1.948997   1.948997
              2          2.324756   2.324756   2.324756   2.324756   2.324756

LSOA2021                E01008167  E01008170  E01008172  E01008173  E01008174  \
ns_sec adults children
1      1      1          1.971195   1.971195   1.971195   1.971195   1.971195
              2          2.346954   2.346954   2.346954   2.346954   2.346954
       2      1          3.107935   3.107935   3.107935   3.107935   3.107935
              2          3.483694   3.483694   3.483694   3.483694   3.483694
       3      1          3.191446   3.191446   3.191446   3.191446   3.191446
              2          3.567205   3.567205   3.567205   3.567205   3.567205
2      1      1          1.662489   1.662489   1.662489   1.662489   1.662489
              2          2.038248   2.038248   2.038248   2.038248   2.038248
       2      1          2.799229   2.799229   2.799229   2.799229   2.799229
              2          3.174988   3.174988   3.174988   3.174988   3.174988
       3      1          2.882740   2.882740   2.882740   2.882740   2.882740
              2          3.258500   3.258500   3.258500   3.258500   3.258500
3      1      1          0.945572   0.945572   0.945572   0.945572   0.945572
              2          1.321332   1.321332   1.321332   1.321332   1.321332
       2      1          2.082313   2.082313   2.082313   2.082313   2.082313
              2          2.458072   2.458072   2.458072   2.458072   2.458072
       3      1          2.165824   2.165824   2.165824   2.165824   2.165824
              2          2.541583   2.541583   2.541583   2.541583   2.541583
4      1      1          0.149380   0.149380   0.149380   0.149380   0.149380
              2          0.525139   0.525139   0.525139   0.525139   0.525139
       2      1          1.286120   1.286120   1.286120   1.286120   1.286120
              2          1.661879   1.661879   1.661879   1.661879   1.661879
       3      1          1.369632   1.369632   1.369632   1.369632   1.369632
              2          1.745391   1.745391   1.745391   1.745391   1.745391
5      1      1          0.728745   0.728745   0.728745   0.728745   0.728745
              2          1.104504   1.104504   1.104504   1.104504   1.104504
       2      1          1.865485   1.865485   1.865485   1.865485   1.865485
              2          2.241245   2.241245   2.241245   2.241245   2.241245
       3      1          1.948997   1.948997   1.948997   1.948997   1.948997
              2          2.324756   2.324756   2.324756   2.324756   2.324756

LSOA2021                ...  E01035628  E01035629  E01035630  E01035631  \
ns_sec adults children  ...
1      1      1         ...   1.971195   1.971195   1.971195   1.971195
              2         ...   2.346954   2.346954   2.346954   2.346954
       2      1         ...   3.107935   3.107935   3.107935   3.107935
              2         ...   3.483694   3.483694   3.483694   3.483694
       3      1         ...   3.191446   3.191446   3.191446   3.191446
              2         ...   3.567205   3.567205   3.567205   3.567205
2      1      1         ...   1.662489   1.662489   1.662489   1.662489
              2         ...   2.038248   2.038248   2.038248   2.038248
       2      1         ...   2.799229   2.799229   2.799229   2.799229
              2         ...   3.174988   3.174988   3.174988   3.174988
       3      1         ...   2.882740   2.882740   2.882740   2.882740
              2         ...   3.258500   3.258500   3.258500   3.258500
3      1      1         ...   0.945572   0.945572   0.945572   0.945572
              2         ...   1.321332   1.321332   1.321332   1.321332
       2      1         ...   2.082313   2.082313   2.082313   2.082313
              2         ...   2.458072   2.458072   2.458072   2.458072
       3      1         ...   2.165824   2.165824   2.165824   2.165824
              2         ...   2.541583   2.541583   2.541583   2.541583
4      1      1         ...   0.149380   0.149380   0.149380   0.149380
              2         ...   0.525139   0.525139   0.525139   0.525139
       2      1         ...   1.286120   1.286120   1.286120   1.286120
              2         ...   1.661879   1.661879   1.661879   1.661879
       3      1         ...   1.369632   1.369632   1.369632   1.369632
              2         ...   1.745391   1.745391   1.745391   1.745391
5      1      1         ...   0.728745   0.728745   0.728745   0.728745
              2         ...   1.104504   1.104504   1.104504   1.104504
       2      1         ...   1.865485   1.865485   1.865485   1.865485
              2         ...   2.241245   2.241245   2.241245   2.241245
       3      1         ...   1.948997   1.948997   1.948997   1.948997
              2         ...   2.324756   2.324756   2.324756   2.324756

LSOA2021                E01035632  E01035633  E01035634  E01035635  E01035636  \
ns_sec adults children
1      1      1          1.971195   1.971195   1.971195   1.971195   1.971195
              2          2.346954   2.346954   2.346954   2.346954   2.346954
       2      1          3.107935   3.107935   3.107935   3.107935   3.107935
              2          3.483694   3.483694   3.483694   3.483694   3.483694
       3      1          3.191446   3.191446   3.191446   3.191446   3.191446
              2          3.567205   3.567205   3.567205   3.567205   3.567205
2      1      1          1.662489   1.662489   1.662489   1.662489   1.662489
              2          2.038248   2.038248   2.038248   2.038248   2.038248
       2      1          2.799229   2.799229   2.799229   2.799229   2.799229
              2          3.174988   3.174988   3.174988   3.174988   3.174988
       3      1          2.882740   2.882740   2.882740   2.882740   2.882740
              2          3.258500   3.258500   3.258500   3.258500   3.258500
3      1      1          0.945572   0.945572   0.945572   0.945572   0.945572
              2          1.321332   1.321332   1.321332   1.321332   1.321332
       2      1          2.082313   2.082313   2.082313   2.082313   2.082313
              2          2.458072   2.458072   2.458072   2.458072   2.458072
       3      1          2.165824   2.165824   2.165824   2.165824   2.165824
              2          2.541583   2.541583   2.541583   2.541583   2.541583
4      1      1          0.149380   0.149380   0.149380   0.149380   0.149380
              2          0.525139   0.525139   0.525139   0.525139   0.525139
       2      1          1.286120   1.286120   1.286120   1.286120   1.286120
              2          1.661879   1.661879   1.661879   1.661879   1.661879
       3      1          1.369632   1.369632   1.369632   1.369632   1.369632
              2          1.745391   1.745391   1.745391   1.745391   1.745391
5      1      1          0.728745   0.728745   0.728745   0.728745   0.728745
              2          1.104504   1.104504   1.104504   1.104504   1.104504
       2      1          1.865485   1.865485   1.865485   1.865485   1.865485
              2          2.241245   2.241245   2.241245   2.241245   2.241245
       3      1          1.948997   1.948997   1.948997   1.948997   1.948997
              2          2.324756   2.324756   2.324756   2.324756   2.324756

LSOA2021                E01035637
ns_sec adults children
1      1      1          1.971195
              2          2.346954
       2      1          3.107935
              2          3.483694
       3      1          3.191446
              2          3.567205
2      1      1          1.662489
              2          2.038248
       2      1          2.799229
              2          3.174988
       3      1          2.882740
              2          3.258500
3      1      1          0.945572
              2          1.321332
       2      1          2.082313
              2          2.458072
       3      1          2.165824
              2          2.541583
4      1      1          0.149380
              2          0.525139
       2      1          1.286120
              2          1.661879
       3      1          1.369632
              2          1.745391
5      1      1          0.728745
              2          1.104504
       2      1          1.865485
              2          2.241245
       3      1          1.948997
              2          2.324756

[30 rows x 1682 columns]

In [18]:
# get DVector of 'e's to apply df.pow to (i.e. we need to do e^-model_totals to get the logit application)
exponential = (model_totals.copy() * 0) + math.e
exponential.data = exponential.data.pow(-model_totals.data)
exponential.data

LSOA2021                E01008162  E01008163  E01008164  E01008165  E01008166  \
ns_sec adults children
1      1      1          0.139290   0.139290   0.139290   0.139290   0.139290
              2          0.095660   0.095660   0.095660   0.095660   0.095660
       2      1          0.044693   0.044693   0.044693   0.044693   0.044693
              2          0.030694   0.030694   0.030694   0.030694   0.030694
       3      1          0.041112   0.041112   0.041112   0.041112   0.041112
              2          0.028235   0.028235   0.028235   0.028235   0.028235
2      1      1          0.189666   0.189666   0.189666   0.189666   0.189666
              2          0.130257   0.130257   0.130257   0.130257   0.130257
       2      1          0.060857   0.060857   0.060857   0.060857   0.060857
              2          0.041795   0.041795   0.041795   0.041795   0.041795
       3      1          0.055981   0.055981   0.055981   0.055981   0.055981
              2          0.038446   0.038446   0.038446   0.038446   0.038446
3      1      1          0.388457   0.388457   0.388457   0.388457   0.388457
              2          0.266780   0.266780   0.266780   0.266780   0.266780
       2      1          0.124642   0.124642   0.124642   0.124642   0.124642
              2          0.085600   0.085600   0.085600   0.085600   0.085600
       3      1          0.114655   0.114655   0.114655   0.114655   0.114655
              2          0.078742   0.078742   0.078742   0.078742   0.078742
4      1      1          0.861242   0.861242   0.861242   0.861242   0.861242
              2          0.591473   0.591473   0.591473   0.591473   0.591473
       2      1          0.276341   0.276341   0.276341   0.276341   0.276341
              2          0.189782   0.189782   0.189782   0.189782   0.189782
       3      1          0.254201   0.254201   0.254201   0.254201   0.254201
              2          0.174577   0.174577   0.174577   0.174577   0.174577
5      1      1          0.482514   0.482514   0.482514   0.482514   0.482514
              2          0.331375   0.331375   0.331375   0.331375   0.331375
       2      1          0.154821   0.154821   0.154821   0.154821   0.154821
              2          0.106326   0.106326   0.106326   0.106326   0.106326
       3      1          0.142417   0.142417   0.142417   0.142417   0.142417
              2          0.097807   0.097807   0.097807   0.097807   0.097807

LSOA2021                E01008167  E01008170  E01008172  E01008173  E01008174  \
ns_sec adults children
1      1      1          0.139290   0.139290   0.139290   0.139290   0.139290
              2          0.095660   0.095660   0.095660   0.095660   0.095660
       2      1          0.044693   0.044693   0.044693   0.044693   0.044693
              2          0.030694   0.030694   0.030694   0.030694   0.030694
       3      1          0.041112   0.041112   0.041112   0.041112   0.041112
              2          0.028235   0.028235   0.028235   0.028235   0.028235
2      1      1          0.189666   0.189666   0.189666   0.189666   0.189666
              2          0.130257   0.130257   0.130257   0.130257   0.130257
       2      1          0.060857   0.060857   0.060857   0.060857   0.060857
              2          0.041795   0.041795   0.041795   0.041795   0.041795
       3      1          0.055981   0.055981   0.055981   0.055981   0.055981
              2          0.038446   0.038446   0.038446   0.038446   0.038446
3      1      1          0.388457   0.388457   0.388457   0.388457   0.388457
              2          0.266780   0.266780   0.266780   0.266780   0.266780
       2      1          0.124642   0.124642   0.124642   0.124642   0.124642
              2          0.085600   0.085600   0.085600   0.085600   0.085600
       3      1          0.114655   0.114655   0.114655   0.114655   0.114655
              2          0.078742   0.078742   0.078742   0.078742   0.078742
4      1      1          0.861242   0.861242   0.861242   0.861242   0.861242
              2          0.591473   0.591473   0.591473   0.591473   0.591473
       2      1          0.276341   0.276341   0.276341   0.276341   0.276341
              2          0.189782   0.189782   0.189782   0.189782   0.189782
       3      1          0.254201   0.254201   0.254201   0.254201   0.254201
              2          0.174577   0.174577   0.174577   0.174577   0.174577
5      1      1          0.482514   0.482514   0.482514   0.482514   0.482514
              2          0.331375   0.331375   0.331375   0.331375   0.331375
       2      1          0.154821   0.154821   0.154821   0.154821   0.154821
              2          0.106326   0.106326   0.106326   0.106326   0.106326
       3      1          0.142417   0.142417   0.142417   0.142417   0.142417
              2          0.097807   0.097807   0.097807   0.097807   0.097807

LSOA2021                ...  E01035628  E01035629  E01035630  E01035631  \
ns_sec adults children  ...
1      1      1         ...   0.139290   0.139290   0.139290   0.139290
              2         ...   0.095660   0.095660   0.095660   0.095660
       2      1         ...   0.044693   0.044693   0.044693   0.044693
              2         ...   0.030694   0.030694   0.030694   0.030694
       3      1         ...   0.041112   0.041112   0.041112   0.041112
              2         ...   0.028235   0.028235   0.028235   0.028235
2      1      1         ...   0.189666   0.189666   0.189666   0.189666
              2         ...   0.130257   0.130257   0.130257   0.130257
       2      1         ...   0.060857   0.060857   0.060857   0.060857
              2         ...   0.041795   0.041795   0.041795   0.041795
       3      1         ...   0.055981   0.055981   0.055981   0.055981
              2         ...   0.038446   0.038446   0.038446   0.038446
3      1      1         ...   0.388457   0.388457   0.388457   0.388457
              2         ...   0.266780   0.266780   0.266780   0.266780
       2      1         ...   0.124642   0.124642   0.124642   0.124642
              2         ...   0.085600   0.085600   0.085600   0.085600
       3      1         ...   0.114655   0.114655   0.114655   0.114655
              2         ...   0.078742   0.078742   0.078742   0.078742
4      1      1         ...   0.861242   0.861242   0.861242   0.861242
              2         ...   0.591473   0.591473   0.591473   0.591473
       2      1         ...   0.276341   0.276341   0.276341   0.276341
              2         ...   0.189782   0.189782   0.189782   0.189782
       3      1         ...   0.254201   0.254201   0.254201   0.254201
              2         ...   0.174577   0.174577   0.174577   0.174577
5      1      1         ...   0.482514   0.482514   0.482514   0.482514
              2         ...   0.331375   0.331375   0.331375   0.331375
       2      1         ...   0.154821   0.154821   0.154821   0.154821
              2         ...   0.106326   0.106326   0.106326   0.106326
       3      1         ...   0.142417   0.142417   0.142417   0.142417
              2         ...   0.097807   0.097807   0.097807   0.097807

LSOA2021                E01035632  E01035633  E01035634  E01035635  E01035636  \
ns_sec adults children
1      1      1          0.139290   0.139290   0.139290   0.139290   0.139290
              2          0.095660   0.095660   0.095660   0.095660   0.095660
       2      1          0.044693   0.044693   0.044693   0.044693   0.044693
              2          0.030694   0.030694   0.030694   0.030694   0.030694
       3      1          0.041112   0.041112   0.041112   0.041112   0.041112
              2          0.028235   0.028235   0.028235   0.028235   0.028235
2      1      1          0.189666   0.189666   0.189666   0.189666   0.189666
              2          0.130257   0.130257   0.130257   0.130257   0.130257
       2      1          0.060857   0.060857   0.060857   0.060857   0.060857
              2          0.041795   0.041795   0.041795   0.041795   0.041795
       3      1          0.055981   0.055981   0.055981   0.055981   0.055981
              2          0.038446   0.038446   0.038446   0.038446   0.038446
3      1      1          0.388457   0.388457   0.388457   0.388457   0.388457
              2          0.266780   0.266780   0.266780   0.266780   0.266780
       2      1          0.124642   0.124642   0.124642   0.124642   0.124642
              2          0.085600   0.085600   0.085600   0.085600   0.085600
       3      1          0.114655   0.114655   0.114655   0.114655   0.114655
              2          0.078742   0.078742   0.078742   0.078742   0.078742
4      1      1          0.861242   0.861242   0.861242   0.861242   0.861242
              2          0.591473   0.591473   0.591473   0.591473   0.591473
       2      1          0.276341   0.276341   0.276341   0.276341   0.276341
              2          0.189782   0.189782   0.189782   0.189782   0.189782
       3      1          0.254201   0.254201   0.254201   0.254201   0.254201
              2          0.174577   0.174577   0.174577   0.174577   0.174577
5      1      1          0.482514   0.482514   0.482514   0.482514   0.482514
              2          0.331375   0.331375   0.331375   0.331375   0.331375
       2      1          0.154821   0.154821   0.154821   0.154821   0.154821
              2          0.106326   0.106326   0.106326   0.106326   0.106326
       3      1          0.142417   0.142417   0.142417   0.142417   0.142417
              2          0.097807   0.097807   0.097807   0.097807   0.097807

LSOA2021                E01035637
ns_sec adults children
1      1      1          0.139290
              2          0.095660
       2      1          0.044693
              2          0.030694
       3      1          0.041112
              2          0.028235
2      1      1          0.189666
              2          0.130257
       2      1          0.060857
              2          0.041795
       3      1          0.055981
              2          0.038446
3      1      1          0.388457
              2          0.266780
       2      1          0.124642
              2          0.085600
       3      1          0.114655
              2          0.078742
4      1      1          0.861242
              2          0.591473
       2      1          0.276341
              2          0.189782
       3      1          0.254201
              2          0.174577
5      1      1          0.482514
              2          0.331375
       2      1          0.154821
              2          0.106326
       3      1          0.142417
              2          0.097807

[30 rows x 1682 columns]

In [19]:
# calculate the probabilities from the logit model
probabilities = exponential.copy()
probabilities.data = 1 / (probabilities.data.add(1))
probabilities.data

LSOA2021                E01008162  E01008163  E01008164  E01008165  E01008166  \
ns_sec adults children
1      1      1          0.877739   0.877739   0.877739   0.877739   0.877739
              2          0.912692   0.912692   0.912692   0.912692   0.912692
       2      1          0.957219   0.957219   0.957219   0.957219   0.957219
              2          0.970220   0.970220   0.970220   0.970220   0.970220
       3      1          0.960511   0.960511   0.960511   0.960511   0.960511
              2          0.972541   0.972541   0.972541   0.972541   0.972541
2      1      1          0.840572   0.840572   0.840572   0.840572   0.840572
              2          0.884755   0.884755   0.884755   0.884755   0.884755
       2      1          0.942634   0.942634   0.942634   0.942634   0.942634
              2          0.959882   0.959882   0.959882   0.959882   0.959882
       3      1          0.946987   0.946987   0.946987   0.946987   0.946987
              2          0.962977   0.962977   0.962977   0.962977   0.962977
3      1      1          0.720224   0.720224   0.720224   0.720224   0.720224
              2          0.789403   0.789403   0.789403   0.789403   0.789403
       2      1          0.889172   0.889172   0.889172   0.889172   0.889172
              2          0.921150   0.921150   0.921150   0.921150   0.921150
       3      1          0.897138   0.897138   0.897138   0.897138   0.897138
              2          0.927006   0.927006   0.927006   0.927006   0.927006
4      1      1          0.537276   0.537276   0.537276   0.537276   0.537276
              2          0.628349   0.628349   0.628349   0.628349   0.628349
       2      1          0.783490   0.783490   0.783490   0.783490   0.783490
              2          0.840490   0.840490   0.840490   0.840490   0.840490
       3      1          0.797321   0.797321   0.797321   0.797321   0.797321
              2          0.851371   0.851371   0.851371   0.851371   0.851371
5      1      1          0.674530   0.674530   0.674530   0.674530   0.674530
              2          0.751103   0.751103   0.751103   0.751103   0.751103
       2      1          0.865935   0.865935   0.865935   0.865935   0.865935
              2          0.903893   0.903893   0.903893   0.903893   0.903893
       3      1          0.875337   0.875337   0.875337   0.875337   0.875337
              2          0.910907   0.910907   0.910907   0.910907   0.910907

LSOA2021                E01008167  E01008170  E01008172  E01008173  E01008174  \
ns_sec adults children
1      1      1          0.877739   0.877739   0.877739   0.877739   0.877739
              2          0.912692   0.912692   0.912692   0.912692   0.912692
       2      1          0.957219   0.957219   0.957219   0.957219   0.957219
              2          0.970220   0.970220   0.970220   0.970220   0.970220
       3      1          0.960511   0.960511   0.960511   0.960511   0.960511
              2          0.972541   0.972541   0.972541   0.972541   0.972541
2      1      1          0.840572   0.840572   0.840572   0.840572   0.840572
              2          0.884755   0.884755   0.884755   0.884755   0.884755
       2      1          0.942634   0.942634   0.942634   0.942634   0.942634
              2          0.959882   0.959882   0.959882   0.959882   0.959882
       3      1          0.946987   0.946987   0.946987   0.946987   0.946987
              2          0.962977   0.962977   0.962977   0.962977   0.962977
3      1      1          0.720224   0.720224   0.720224   0.720224   0.720224
              2          0.789403   0.789403   0.789403   0.789403   0.789403
       2      1          0.889172   0.889172   0.889172   0.889172   0.889172
              2          0.921150   0.921150   0.921150   0.921150   0.921150
       3      1          0.897138   0.897138   0.897138   0.897138   0.897138
              2          0.927006   0.927006   0.927006   0.927006   0.927006
4      1      1          0.537276   0.537276   0.537276   0.537276   0.537276
              2          0.628349   0.628349   0.628349   0.628349   0.628349
       2      1          0.783490   0.783490   0.783490   0.783490   0.783490
              2          0.840490   0.840490   0.840490   0.840490   0.840490
       3      1          0.797321   0.797321   0.797321   0.797321   0.797321
              2          0.851371   0.851371   0.851371   0.851371   0.851371
5      1      1          0.674530   0.674530   0.674530   0.674530   0.674530
              2          0.751103   0.751103   0.751103   0.751103   0.751103
       2      1          0.865935   0.865935   0.865935   0.865935   0.865935
              2          0.903893   0.903893   0.903893   0.903893   0.903893
       3      1          0.875337   0.875337   0.875337   0.875337   0.875337
              2          0.910907   0.910907   0.910907   0.910907   0.910907

LSOA2021                ...  E01035628  E01035629  E01035630  E01035631  \
ns_sec adults children  ...
1      1      1         ...   0.877739   0.877739   0.877739   0.877739
              2         ...   0.912692   0.912692   0.912692   0.912692
       2      1         ...   0.957219   0.957219   0.957219   0.957219
              2         ...   0.970220   0.970220   0.970220   0.970220
       3      1         ...   0.960511   0.960511   0.960511   0.960511
              2         ...   0.972541   0.972541   0.972541   0.972541
2      1      1         ...   0.840572   0.840572   0.840572   0.840572
              2         ...   0.884755   0.884755   0.884755   0.884755
       2      1         ...   0.942634   0.942634   0.942634   0.942634
              2         ...   0.959882   0.959882   0.959882   0.959882
       3      1         ...   0.946987   0.946987   0.946987   0.946987
              2         ...   0.962977   0.962977   0.962977   0.962977
3      1      1         ...   0.720224   0.720224   0.720224   0.720224
              2         ...   0.789403   0.789403   0.789403   0.789403
       2      1         ...   0.889172   0.889172   0.889172   0.889172
              2         ...   0.921150   0.921150   0.921150   0.921150
       3      1         ...   0.897138   0.897138   0.897138   0.897138
              2         ...   0.927006   0.927006   0.927006   0.927006
4      1      1         ...   0.537276   0.537276   0.537276   0.537276
              2         ...   0.628349   0.628349   0.628349   0.628349
       2      1         ...   0.783490   0.783490   0.783490   0.783490
              2         ...   0.840490   0.840490   0.840490   0.840490
       3      1         ...   0.797321   0.797321   0.797321   0.797321
              2         ...   0.851371   0.851371   0.851371   0.851371
5      1      1         ...   0.674530   0.674530   0.674530   0.674530
              2         ...   0.751103   0.751103   0.751103   0.751103
       2      1         ...   0.865935   0.865935   0.865935   0.865935
              2         ...   0.903893   0.903893   0.903893   0.903893
       3      1         ...   0.875337   0.875337   0.875337   0.875337
              2         ...   0.910907   0.910907   0.910907   0.910907

LSOA2021                E01035632  E01035633  E01035634  E01035635  E01035636  \
ns_sec adults children
1      1      1          0.877739   0.877739   0.877739   0.877739   0.877739
              2          0.912692   0.912692   0.912692   0.912692   0.912692
       2      1          0.957219   0.957219   0.957219   0.957219   0.957219
              2          0.970220   0.970220   0.970220   0.970220   0.970220
       3      1          0.960511   0.960511   0.960511   0.960511   0.960511
              2          0.972541   0.972541   0.972541   0.972541   0.972541
2      1      1          0.840572   0.840572   0.840572   0.840572   0.840572
              2          0.884755   0.884755   0.884755   0.884755   0.884755
       2      1          0.942634   0.942634   0.942634   0.942634   0.942634
              2          0.959882   0.959882   0.959882   0.959882   0.959882
       3      1          0.946987   0.946987   0.946987   0.946987   0.946987
              2          0.962977   0.962977   0.962977   0.962977   0.962977
3      1      1          0.720224   0.720224   0.720224   0.720224   0.720224
              2          0.789403   0.789403   0.789403   0.789403   0.789403
       2      1          0.889172   0.889172   0.889172   0.889172   0.889172
              2          0.921150   0.921150   0.921150   0.921150   0.921150
       3      1          0.897138   0.897138   0.897138   0.897138   0.897138
              2          0.927006   0.927006   0.927006   0.927006   0.927006
4      1      1          0.537276   0.537276   0.537276   0.537276   0.537276
              2          0.628349   0.628349   0.628349   0.628349   0.628349
       2      1          0.783490   0.783490   0.783490   0.783490   0.783490
              2          0.840490   0.840490   0.840490   0.840490   0.840490
       3      1          0.797321   0.797321   0.797321   0.797321   0.797321
              2          0.851371   0.851371   0.851371   0.851371   0.851371
5      1      1          0.674530   0.674530   0.674530   0.674530   0.674530
              2          0.751103   0.751103   0.751103   0.751103   0.751103
       2      1          0.865935   0.865935   0.865935   0.865935   0.865935
              2          0.903893   0.903893   0.903893   0.903893   0.903893
       3      1          0.875337   0.875337   0.875337   0.875337   0.875337
              2          0.910907   0.910907   0.910907   0.910907   0.910907

LSOA2021                E01035637
ns_sec adults children
1      1      1          0.877739
              2          0.912692
       2      1          0.957219
              2          0.970220
       3      1          0.960511
              2          0.972541
2      1      1          0.840572
              2          0.884755
       2      1          0.942634
              2          0.959882
       3      1          0.946987
              2          0.962977
3      1      1          0.720224
              2          0.789403
       2      1          0.889172
              2          0.921150
       3      1          0.897138
              2          0.927006
4      1      1          0.537276
              2          0.628349
       2      1          0.783490
              2          0.840490
       3      1          0.797321
              2          0.851371
5      1      1          0.674530
              2          0.751103
       2      1          0.865935
              2          0.903893
       3      1          0.875337
              2          0.910907

[30 rows x 1682 columns]

In [20]:
_1_plus = probabilities * hh_data_aggregated
_no_car = hh_data_aggregated - _1_plus

In [21]:
_1_plus.data

LSOA2021                 E01008162  E01008163  E01008164  E01008165  \
ns_sec adults children
1      1      1         181.431043  71.856417  48.125004  21.385913
              2           9.873695   6.139214   7.559140   6.995593
       2      1         153.288203  55.940232  51.234218  24.798542
              2          65.544311  42.799450  34.857154  22.567688
       3      1          30.514722  23.043520  10.288968  12.067093
              2           9.739644  20.290878   7.514177   6.068654
2      1      1          91.663584  62.395580  57.613438  29.710595
              2           6.459819   5.382385   7.549495  12.701729
       2      1          83.960532  40.161531  50.342038  35.884683
              2          29.280745  21.287412  20.128008  22.771794
       3      1          21.993038  18.549084   9.764689  20.472282
              2           6.597154  14.749312   6.009058   9.521629
3      1      1          96.271260  68.235122  70.966234  43.710373
              2           7.354856   7.930569  11.352181  25.342644
       2      1          77.434388  48.619386  62.802824  57.970857
              2          20.051458  21.748035  19.896386  28.948559
       3      1          19.367336  24.670930  12.283405  33.537003
              2           5.166011  17.078727   6.640848  13.164667
4      1      1          33.373354  23.885350  32.417316  22.414951
              2           1.900312   2.558180   4.174184  11.085010
       2      1          18.857483  13.071825  22.515995  23.073152
              2           2.842887   3.813564   4.322802   7.650515
       3      1           2.869277   4.702865   2.872447   9.525010
              2           0.689765   2.854276   1.308159   3.525471
5      1      1          15.505777  10.304518   5.046718   2.456152
              2           3.379504   2.977485   2.492677   2.977816
       2      1           8.540596   3.707395   3.355361   1.810559
              2           5.336328   3.089807   2.591716   2.124005
       3      1           2.533349   1.670216   0.798511   1.191569
              2           0.776421   1.048875   0.496558   0.539391

LSOA2021                 E01008166  E01008167   E01008170  E01008172  \
ns_sec adults children
1      1      1         124.643674  50.208083   69.904696  60.520136
              2           0.963070   4.575503    5.385658   7.008988
       2      1          71.412380  53.249122   58.255680  90.406621
              2           7.118454  33.445017   30.443229  34.980981
       3      1           7.682642  17.419795   24.688193  22.298531
              2           0.000000  10.259028   10.228465   9.388312
2      1      1          48.871228  53.349103   74.574829  64.595677
              2           0.459361   5.307955    6.019737   8.003208
       2      1          27.537806  50.655378   48.960712  91.244089
              2           2.509000  22.588721   18.041756  25.366735
       3      1           4.273572  19.046139   22.344429  26.768987
              2           0.000000   9.773961    7.844002  10.222596
3      1      1          78.168829  55.624021  122.939430  64.469325
              2           0.942307   6.837605   12.438811   9.889365
       2      1          44.788255  54.046080   71.456370  77.551161
              2           3.478972  19.403357   20.643003  15.471784
       3      1           7.289000  21.235790   26.932298  22.085205
              2           0.000000   8.889381    8.114590   6.793684
4      1      1          38.758747  28.481619   49.342819  26.988573
              2           0.479198   3.308162    4.966017   3.923664
       2      1          19.693011  21.046033   25.358369  24.185310
              2           1.239983   5.331555    5.306226   2.919960
       3      1           2.780787   5.713460    7.234086   4.572943
              2           0.000000   2.003142    2.133220   1.230344
5      1      1           9.598151   1.835445    3.796435   1.011003
              2           0.346522   0.727411    1.201989   0.324207
       2      1           4.012009   1.411215    1.439170   0.517424
              2           0.721427   1.314821    1.077639   0.226306
       3      1           0.768520   0.707985    0.618890   0.146902
              2           0.000000   0.380153    0.191471   0.049017

LSOA2021                E01008173   E01008174  ...   E01035628   E01035629  \
ns_sec adults children                         ...
1      1      1         18.378388   54.739156  ...   33.944026   45.056354
              2          6.141088    8.285879  ...   12.125730   13.054756
       2      1         26.081017  103.150397  ...  104.066842  127.321747
              2         22.696863   74.975465  ...  144.304278   76.489293
       3      1         14.945827   35.211114  ...   28.101238   32.928094
              2          6.936815   20.288862  ...   15.885701   22.595143
2      1      1         33.099528   53.087431  ...   19.009905   34.585934
              2         11.904986    8.180227  ...    6.846749   11.076727
       2      1         42.457946   71.207713  ...   51.381545   85.398794
              2         25.733274   34.794503  ...   47.061900   42.623763
       3      1         28.086761   26.779653  ...   16.586997   22.117434
              2         12.188625   13.991270  ...    8.274972   13.460522
3      1      1         52.906647   88.451105  ...    9.811426   12.538672
              2         21.556248   14.412689  ...    6.074308    6.113487
       2      1         57.673357   79.125026  ...   25.077944   28.403900
              2         25.199744   25.484862  ...   14.680078   11.327550
       3      1         36.223105   24.512013  ...    8.040045    6.883086
              2         12.643795   10.155919  ...    3.318842    3.645438
4      1      1         20.142586   37.136967  ...    4.159507    4.988447
              2          6.337647    4.339364  ...    1.590011    2.279616
       2      1         15.108613   21.108467  ...    5.682903    8.893940
              2          3.989487    3.865067  ...    1.532329    1.497617
       3      1          6.310769    3.741538  ...    0.968744    1.073705
              2          2.109912    1.481656  ...    0.371396    0.516927
5      1      1          0.706432    0.614683  ...    0.215232    0.335119
              2          1.054582    0.456072  ...    0.591222    0.572075
       2      1          0.685322    0.812815  ...    0.284119    0.230913
              2          0.754619    0.739413  ...    0.427924    0.285815
       3      1          0.568877    0.396059  ...    0.051614    0.078398
              2          0.248211    0.248104  ...    0.030317    0.062947

LSOA2021                 E01035630  E01035631   E01035632  E01035633  \
ns_sec adults children
1      1      1          71.071363  54.108280   62.570824  43.579067
              2          19.478957   9.766461   13.300170   6.936426
       2      1         162.124968  62.567265   89.431628  71.870187
              2          75.365469  30.808242  115.162386  30.741290
       3      1          43.034713  20.675701   26.350548  27.845606
              2          19.288617   8.763611   14.181146   6.801237
2      1      1          31.809181  68.601229   53.214245  36.608008
              2           8.956292  12.612829    9.350450   6.785042
       2      1          64.047563  72.038158   56.158700  57.654946
              2          25.055621  29.723434   55.530641  21.606716
       3      1          17.646410  25.325386   16.721266  24.128218
              2           7.080182   9.630413    7.741548   5.419144
3      1      1          14.123162  57.926623   43.429383  38.760456
              2           6.009885  14.612227    7.107532  10.762264
       2      1          25.007188  62.196442   31.306420  54.398711
              2           7.369233  19.754475   17.520223  17.127441
       3      1           5.859020  20.573100    7.652590  22.081176
              2           1.967515   7.170213    2.723568   4.786912
4      1      1           5.168772  22.785800   12.774944  13.763027
              2           1.739676   4.404911    1.870106   4.117562
       2      1           8.248019  18.515197    8.188960  17.760422
              2           1.074597   2.427342    1.828656   2.640411
       3      1           1.118429   3.047298    0.992932   3.855549
              2           0.342646   1.054156    0.318050   1.009038
5      1      1           0.749449   0.440696    1.583869   0.459877
              2           0.737426   0.565103    0.710779   0.503234
       2      1           0.322148   0.192635    0.249683   0.207793
              2           0.282265   0.186635    0.274807   0.199950
       3      1           0.129711   0.099190    0.072229   0.132223
              2           0.068006   0.047407    0.027963   0.032798

LSOA2021                E01035634   E01035635   E01035636  E01035637
ns_sec adults children
1      1      1         17.946459   52.646224   72.656634  37.276838
              2          2.959839   12.132957    8.570364   3.398142
       2      1         71.457812   95.077062  140.610820  95.336210
              2         30.956179  104.235646   55.027686  34.897356
       3      1         28.371722   14.328154   40.893309  26.850347
              2         15.769566   12.690154   13.271681  10.005348
2      1      1         14.039901   38.537367   72.037569  28.059961
              2          2.358003    9.263872    8.694394   2.517555
       2      1         51.565790   63.361360  104.172955  73.367462
              2         19.336372   59.761940   33.637306  23.309065
       3      1         22.077926   10.321446   32.613670  21.998910
              2         11.045084    7.999045    9.126365   7.151501
3      1      1         10.139911   21.848113   66.290061   8.775315
              2          2.564273    8.188695   10.597072   1.056660
       2      1         30.589424   31.525033   82.485402  16.961349
              2          9.607836   24.902163   20.957549   4.240067
       3      1         13.474289    5.063367   26.073536   5.398868
              2          6.323296    3.855879    6.446300   1.650963
4      1      1          2.477124    1.426422   16.842231   3.699859
              2          0.304610    0.583756    2.265495   0.463871
       2      1          4.312050    1.816730   17.538358   6.772460
              2          0.545027    0.641380    1.865778   0.718366
       3      1          0.974050    0.155087    2.894369   1.184612
              2          0.452018    0.118912    0.691439   0.332904
5      1      1          0.893582    1.036521    0.804376   1.277991
              2          0.303465    1.370643    0.617933   0.264761
       2      1          0.145121    0.579513    0.345838   0.340592
              2          0.054090    1.461775    0.281357   0.158053
       3      1          0.029573    0.144720    0.178771   0.121949
              2          0.009119    0.170103    0.063687   0.041325

[30 rows x 1682 columns]

In [22]:
_no_car.data

LSOA2021                E01008162  E01008163  E01008164  E01008165  E01008166  \
ns_sec adults children
1      1      1         25.271596  10.008907   6.703349   2.978852  17.361663
              2          0.944519   0.587278   0.723108   0.669199   0.092127
       2      1          6.850934   2.500146   2.289819   1.108325   3.191645
              2          2.011805   1.313678   1.069899   0.692688   0.218493
       3      1          1.254533   0.947374   0.423004   0.496107   0.315852
              2          0.274995   0.572906   0.212160   0.171346   0.000000
2      1      1         17.385500  11.834344  10.927332   5.635101   9.269229
              2          0.841435   0.701092   0.983372   1.654486   0.059835
       2      1          5.109584   2.444109   3.063664   2.183833   1.675868
              2          1.223777   0.889699   0.841242   0.951738   0.104863
       3      1          1.231196   1.038399   0.546639   1.146062   0.239239
              2          0.253634   0.567053   0.231025   0.366069   0.000000
3      1      1         37.397264  26.506424  27.567344  16.979609  30.365244
              2          1.962127   2.115716   3.028533   6.760906   0.251388
       2      1          9.651549   6.060000   7.827847   7.225583   5.582482
              2          1.716402   1.861628   1.703128   2.477992   0.297799
       3      1          2.220570   2.828656   1.408359   3.845200   0.835723
              2          0.406780   1.344807   0.522911   1.036607   0.000000
4      1      1         28.742528  20.571062  27.919148  19.304693  33.380654
              2          1.123983   1.513094   2.468917   6.556484   0.283433
       2      1          5.211093   3.612279   6.222089   6.376055   5.441983
              2          0.539529   0.723746   0.820390   1.451930   0.235326
       3      1          0.729372   1.195471   0.730178   2.421263   0.706878
              2          0.120417   0.498290   0.228374   0.615465   0.000000
5      1      1          7.481756   4.972075   2.435113   1.185128   4.631243
              2          1.119883   0.986664   0.826011   0.986774   0.114829
       2      1          1.322264   0.573983   0.519481   0.280313   0.621143
              2          0.567391   0.328527   0.275567   0.225837   0.076707
       3      1          0.360792   0.237867   0.113721   0.169700   0.109450
              2          0.075940   0.102588   0.048567   0.052756   0.000000

LSOA2021                E01008167  E01008170  E01008172  E01008173  E01008174  \
ns_sec adults children
1      1      1          6.993502   9.737051   8.429872   2.559932   7.624637
              2          0.437693   0.515193   0.670481   0.587457   0.792628
       2      1          2.379872   2.603630   4.040558   1.165643   4.610117
              2          1.026555   0.934419   1.073700   0.696653   2.301283
       3      1          0.716169   1.014990   0.916746   0.614458   1.447612
              2          0.289660   0.288797   0.265076   0.195859   0.572849
2      1      1         10.118531  14.144338  12.251628   6.277868  10.068901
              2          0.691397   0.784111   1.042472   1.550705   1.065530
       2      1          3.082733   2.979601   5.552839   2.583862   4.333486
              2          0.944087   0.754048   1.060193   1.075512   1.454222
       3      1          1.066225   1.250867   1.498559   1.572329   1.499156
              2          0.375770   0.301571   0.393018   0.468604   0.537909
3      1      1         21.607551  47.756706  25.043573  20.551968  34.359468
              2          1.824135   3.318424   2.638283   5.750772   3.845015
       2      1          6.736392   8.906439   9.666104   7.188502   9.862273
              2          1.660924   1.767038   1.324382   2.157094   2.181500
       3      1          2.434799   3.087934   2.532189   4.153176   2.810436
              2          0.699964   0.638956   0.534946   0.995593   0.799694
4      1      1         24.529561  42.496099  23.243687  17.347637  31.983909
              2          1.956688   2.937265   2.320741   3.748547   2.566616
       2      1          5.815879   7.007553   6.683389   4.175127   5.833132
              2          1.011833   1.007026   0.554156   0.757133   0.733520
       3      1          1.452365   1.838909   1.162445   1.604201   0.951101
              2          0.349702   0.372411   0.214789   0.368342   0.258663
5      1      1          0.885628   1.831834   0.487823   0.340863   0.296593
              2          0.241046   0.398309   0.107434   0.349462   0.151131
       2      1          0.218486   0.222814   0.080108   0.106102   0.125841
              2          0.139800   0.114581   0.024062   0.080236   0.078619
       3      1          0.100829   0.088140   0.020921   0.081018   0.056405
              2          0.037182   0.018727   0.004794   0.024277   0.024266

LSOA2021                ...  E01035628  E01035629  E01035630  E01035631  \
ns_sec adults children  ...
1      1      1         ...   4.728076   6.275916   9.899556   7.536762
              2         ...   1.159949   1.248819   1.863359   0.934261
       2      1         ...   4.651076   5.690411   7.245877   2.796329
              2         ...   4.429249   2.347748   2.313254   0.945622
       3      1         ...   1.155309   1.353752   1.769259   0.850027
              2         ...   0.448527   0.637966   0.544607   0.247437
2      1      1         ...   3.605540   6.559789   6.033132  13.011347
              2         ...   0.891835   1.442818   1.166617   1.642906
       2      1         ...   3.126925   5.197112   3.897741   4.384024
              2         ...   1.966933   1.781443   1.047190   1.242279
       3      1         ...   0.928559   1.238159   0.987866   1.417744
              2         ...   0.318140   0.517504   0.272205   0.370251
3      1      1         ...   3.811319   4.870737   5.486244  22.502014
              2         ...   1.620503   1.630955   1.603316   3.898247
       2      1         ...   3.125756   3.540309   3.116937   7.752267
              2         ...   1.256612   0.969636   0.630805   1.690980
       3      1         ...   0.921835   0.789183   0.671768   2.358818
              2         ...   0.261331   0.287048   0.154925   0.564594
4      1      1         ...   3.582342   4.296259   4.451562  19.624084
              2         ...   0.940449   1.348331   1.028971   2.605386
       2      1         ...   1.570418   2.457759   2.279265   5.116505
              2         ...   0.290808   0.284221   0.203939   0.460666
       3      1         ...   0.246255   0.272936   0.284305   0.774625
              2         ...   0.064837   0.090243   0.059818   0.184031
5      1      1         ...   0.103852   0.161700   0.361620   0.212642
              2         ...   0.195916   0.189571   0.244364   0.187261
       2      1         ...   0.043988   0.035750   0.049875   0.029824
              2         ...   0.045500   0.030390   0.030012   0.019844
       3      1         ...   0.007351   0.011165   0.018473   0.014126
              2         ...   0.002965   0.006157   0.006651   0.004637

LSOA2021                E01035632  E01035633  E01035634  E01035635  E01035636  \
ns_sec adults children
1      1      1          8.715513   6.070144   2.499769   7.333112  10.120369
              2          1.272296   0.663539   0.283139   1.160640   0.819842
       2      1          3.996982   3.212106   3.193675   4.249294   6.284342
              2          3.534773   0.943568   0.950163   3.199390   1.689010
       3      1          1.083334   1.144799   1.166429   0.589064   1.681221
              2          0.400400   0.192031   0.445248   0.358302   0.374721
2      1      1         10.092953   6.943308   2.662897   7.309243  13.663105
              2          1.217959   0.883797   0.307146   1.206682   1.132503
       2      1          3.417649   3.508705   3.138138   3.855981   6.339651
              2          2.320881   0.903044   0.808156   2.497726   1.405858
       3      1          0.936076   1.350725   1.235948   0.577806   1.825751
              2          0.297632   0.208345   0.424640   0.307532   0.350873
3      1      1         16.870456  15.056778   3.938921   8.487057  25.750851
              2          1.896146   2.871155   0.684096   2.184579   2.827085
       2      1          3.902084   6.780345   3.812716   3.929332  10.281116
              2          1.499728   1.466106   0.822429   2.131621   1.793963
       3      1          0.877411   2.531727   1.544900   0.580543   2.989473
              2          0.214458   0.376929   0.497907   0.303618   0.507592
4      1      1         11.002316  11.853294   2.133403   1.228495  14.505233
              2          1.106117   2.435426   0.180169   0.345276   1.339979
       2      1          2.262944   4.907930   1.191596   0.502037   4.846565
              2          0.347046   0.501102   0.103436   0.121722   0.354091
       3      1          0.252404   0.980083   0.247604   0.039423   0.735750
              2          0.055524   0.176155   0.078912   0.020759   0.120709
5      1      1          0.764239   0.221897   0.431166   0.500136   0.388123
              2          0.235535   0.166759   0.100561   0.454197   0.204768
       2      1          0.038656   0.032171   0.022468   0.089721   0.053543
              2          0.029219   0.021260   0.005751   0.155425   0.029916
       3      1          0.010287   0.018831   0.004212   0.020611   0.025460
              2          0.002735   0.003208   0.000892   0.016637   0.006229

LSOA2021                E01035637
ns_sec adults children
1      1      1          5.192304
              2          0.325067
       2      1          4.260877
              2          1.071133
       3      1          1.103881
              2          0.282497
2      1      1          5.322031
              2          0.327929
       2      1          4.464922
              2          0.974193
       3      1          1.231524
              2          0.274947
3      1      1          3.408834
              2          0.281896
       2      1          2.114090
              2          0.362949
       3      1          0.619010
              2          0.130000
4      1      1          3.186473
              2          0.274367
       2      1          1.871507
              2          0.136333
       3      1          0.301129
              2          0.058117
5      1      1          0.616649
              2          0.087735
       2      1          0.052731
              2          0.016805
       3      1          0.017368
              2          0.004042

[30 rows x 1682 columns]

In [ ]:
# TODO: then this would be applied in the sub model again of 1v2+