In [1]:
from pathlib import Path

import pandas as pd

In [2]:
input_path = Path(r'I:\NorMITs NorCOM\Import')

In [3]:
# read in the processed nts hh dataset 
nts_data = pd.read_csv(input_path / 'NTS' / 'nts_hh_data_v2.csv')

In [4]:
nts_data.head()

,psuid,psugor_b02id,psucounty_b01id,surveyyear,hholdoslaua_b01id,hholdgor_b02id,settlement2011ew_b01id,hholdareatype2_b01id,hholdua1998_b01id,hholdua2009_b01id,...,deflated_total_cost,hh_income_banded_v1,hh_income_banded_v2,0v1_car,1v2+_car,hh_adults_seg,hh_children_seg,tfn_at_v1,tfn_at_v2,hh_income_banded_v3
0,2002000001,7,80,2002,E09000023,7,A1,1,800,800,...,0.522419,3,4,1,2,2,2,1,1,5
1,2002000001,7,80,2002,E09000023,7,A1,1,800,800,...,0.522419,1,1,0,-1,1,1,1,1,2
2,2002000001,7,80,2002,E09000023,7,A1,1,800,800,...,0.522419,5,6,1,2,3,1,1,1,7
3,2002000001,7,80,2002,E09000023,7,A1,1,800,800,...,0.522419,5,6,1,2,2,1,1,1,7
4,2002000001,7,80,2002,E09000023,7,A1,1,800,800,...,0.522419,5,6,1,2,3,1,1,1,7

In [5]:
nts_data.columns

Index(['psuid', 'psugor_b02id', 'psucounty_b01id', 'surveyyear',
       'hholdoslaua_b01id', 'hholdgor_b02id', 'settlement2011ew_b01id',
       'hholdareatype2_b01id', 'hholdua1998_b01id', 'hholdua2009_b01id',
       'hholdnumadults', 'hholdnumchildren', 'numcarvan', 'hhincome2002_b01id',
       'w1', 'w2', 'w3', 'hholdcounty_b01id', 'walkbus', 'walkbus_b01id',
       'getbus_b01id', 'walkrail', 'walkrail_b01id', 'walkrailalt',
       'descta_b01id', 'hholdareatype1_b01id', 'hholdua_b01id',
       'hholdareatype_b01id', 'hholdruc2011_b01id', 'tfn_at', 'hh_type',
       'hh_child', 'ns', 'hh_income', 'householdid', 'rpi', '2023_deflator',
       'hh_income_2023', 'purchase_cost', 'maintenance_cost', 'fuel_cost',
       'insurance_cost', 'total_cost', 'gdp_pc', 'gdp_2023', 'gdp_deflator',
       'deflated_purchase_cost', 'deflated_maintenance_cost',
       'deflated_fuel_cost', 'deflated_insurance_cost', 'deflated_total_cost',
       'hh_income_banded_v1', 'hh_income_banded_v2', '0v1_car', '1v2+_car',
       'hh_adults_seg', 'hh_children_seg', 'tfn_at_v1', 'tfn_at_v2',
       'hh_income_banded_v3'],
      dtype='object')

In [6]:
pt_access_cols = ['walkrail_b01id', 'descta_b01id']

In [7]:
nts_data.groupby(pt_access_cols).agg({'psuid': 'count'})

                             psuid
walkrail_b01id descta_b01id
-10            -10           60833
 1              1             5038
                2              236
                3              385
 2              1             8394
                2              364
                3              589
 3              1            19693
                2              864
                3             1400
 4              1            13385
                2              664
                3              905
 5              1            31211
                2             1645
                3             2519